<?php

// -----------------------------------------
// semplice
// admin/atts/partials/mobile/accordion.php
// -----------------------------------------


// type
if($args['type'] == 'general') {
	$options = array(
		'title'  	 => $title . ' Options',
		'break'		 => '2',
		'class'		 		=> 'mobile-option mobile-option-' .$breakpoint,
		'seperator_height_' . $breakpoint => array(
			'title'			=> 'Seperator Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 1,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'accordion',
			'data-has-unit'	=> true,
			'data-range-slider' => 'accordion',
			'data-responsive-option' => 'accordion',
			'responsive'	=> true,
		)
	);
} else if($args['type'] == 'item') {
	$options = array(
		'title'  	 => 'Item options',
		'break'		 => '1,2',
		'class'		 => 'mobile-option mobile-option-' .$breakpoint,
		'style-class'=> 'ep-collapsed',
		'border_radius_' . $breakpoint => array(
			'title'				=> 'Corner Radius',
			'size'				=> 'span4',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
			'responsive'	=> true,
		),
		'padding_ver_' . $breakpoint => array(
			'title'				=> 'Vertical Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 30,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
			'responsive'	=> true,
		),
		'padding_hor_' . $breakpoint => array(
			'title'				=> 'Horizontal Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
			'responsive'	=> true,
		),
	);
} else if($args['type'] == 'title') {
	$options = array(
		'title'  	 => 'Title Formatting',
		'break'		 => '2,2',
		'class'		 => 'mobile-option mobile-option-' .$breakpoint,
		'style-class'=> 'ep-collapsed',
		'title_font_size_' . $breakpoint => array(
			'title'			=> 'Title Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 40,
			'min'			=> 6,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'accordion',
			'data-range-slider' => 'accordion',
			'data-has-unit'	=> true,
			'responsive'	=> true,
		),
		'title_line_height_' . $breakpoint => array(
			'title'			=> 'Title Line Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 50,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'accordion',
			'data-range-slider' => 'accordion',
			'data-has-unit'	=> true,
			'responsive'	=> true,
		),
		'title_letter_spacing_' . $breakpoint => array(
			'title'				=> 'Title Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-has-unit'		=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-range-slider' => 'accordion',
			'responsive'	=> true,
		),
		'title_right_spacing_' . $breakpoint => array(
			'title'				=> 'Title Right Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 60,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
			'responsive'	=> true,
		),
	);
} else if($args['type'] == 'description') {
	$options = array(
		'title'  	 => 'Description Formatting',
		'break'		 => '2,2',
		'class'		 => 'mobile-option mobile-option-' .$breakpoint,
		'style-class'=> 'ep-collapsed',
		'description_font_size_' . $breakpoint => array(
			'title'			=> 'Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 20,
			'min'			=> 6,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'accordion',
			'data-range-slider' => 'accordion',
			'data-has-unit'	=> true,
			'responsive'	=> true,
		),
		'description_line_height_' . $breakpoint => array(
			'title'			=> 'Line Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 30,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'accordion',
			'data-range-slider' => 'accordion',
			'data-has-unit'	=> true,
			'responsive'	=> true,
		),
		'description_letter_spacing_' . $breakpoint => array(
			'title'				=> 'Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-has-unit'		=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-range-slider' => 'accordion',
			'responsive'	=> true,
		),
		'description_spacing_' . $breakpoint => array(
			'title'				=> 'Top Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 20,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
			'responsive'	=> true,
		),
	);
} else if($args['type'] == 'icon') {
	$options = array(
		'title'  	 => 'Expand/Collapse Icon',
		'break'		 => '2',
		'class'		 => 'mobile-option mobile-option-' .$breakpoint,
		'style-class'=> 'ep-collapsed',
		'icon_width_' . $breakpoint  => array(
			'title'				=> 'Width',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 30,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
			'responsive'	=> true,
		),
		'icon_spacing_' . $breakpoint  => array(
			'title'				=> 'Top Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 10,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
			'data-negative'		=> true,
			'responsive'	=> true,
		),
	);
}