<?php

// -----------------------------------------
// semplice
// admin/atts/modules/accordion.php
// -----------------------------------------

$accordion = array(
	'edit-button' => array(
		'title'  	 => 'Options',
		'hide-title' => true,
		'break'		 => '1,1',
		'data-hide-mobile' => true,
		'code' => array(
			'data-input-type' 	=> 'button',
			'title'		 		=> 'Accordion Items',
			'hide-title'		=> true,
			'button-title'		=> 'Edit Accordion',
			'size'		 		=> 'span4',
			'class'				=> 'semplice-button edit-accordion'
		),
		'first_item' => array(
			'data-input-type' 			=> 'switch',
			'switch-type'				=> 'twoway',
			'title'		 				=> 'First item is',
			'size'		 				=> 'span4',
			'class'						=> 'editor-listen',
			'data-handler'				=> 'accordion',
			'default' 	 				=> 'collapsed',
			'help'						=> 'This setting only affects the frontend.',
			'switch-values' => array(
				'collapsed'	=> 'Collapsed',
				'expanded'  => 'Expanded',
			),
		),
	),
	'item-options' => array(
		'title'  	 => 'Item Options',
		'break'		 => '2,2',
		'data-hide-mobile' => true,
		'bg_color' => array(
			'title'				=> 'BG Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#ffffff',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'accordion',
		),
		'border_radius' => array(
			'title'				=> 'Corner Radius',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
			'help'				=> 'Only visible when a background color is defined for the item.',
		),
		'padding_ver' => array(
			'title'				=> 'Vertical Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 30,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
		),
		'padding_hor' => array(
			'title'				=> 'Horizontal Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
		),
	),
	'title-options' => array(
		'title'  	 => 'Title Formatting',
		'break'		 => '2,2,2,2',
		'data-hide-mobile' => true,
		'style-class'=> 'ep-collapsed',
		'title_color' => array(
			'title'				=> 'Text Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#000000',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'accordion'
		),
		'title_text_transform' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Text Transform',
			'size'		 => 'span2',
			'class'			=> 'editor-listen',
			'data-handler'	=> 'accordion',
			'default' 	 => 'none',
			'select-box-values' => array(
				'none'			=> 'None',
				'uppercase'		=> 'Uppercase',
				'lowercase'		=> 'Lowercase'
			),
		),
		'title_font_family' => array(
			'data-input-type' => 'select-fonts',
			'title'		 		=> 'Font Family',
			'size'		 		=> 'span2',
			'class'     		=> 'editor-listen',
			'data-handler'  	=> 'accordion',
			'default' 	 		=> 'none',
			'select-box-values' => $atts->fonts,
		),
		'title_font_size' => array(
			'title'			=> 'Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 40,
			'min'			=> 6,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'accordion',
			'data-range-slider' => 'accordion',
			'data-has-unit'	=> true,
		),
		'title_line_height' => array(
			'title'			=> 'Line Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 50,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'accordion',
			'data-range-slider' => 'accordion',
			'data-has-unit'	=> true,
		),
		'title_letter_spacing' => array(
			'title'				=> 'Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-has-unit'		=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-range-slider' => 'accordion'
		),
		'title_align' => array(
			'data-input-type' 			=> 'switch',
			'switch-type'				=> 'twoway',
			'title'		 				=> 'Align',
			'size'		 				=> 'span2',
			'class'						=> 'editor-listen',
			'data-handler'				=> 'accordion',
			'default' 	 				=> 'left',
			'switch-values' => array(
				'left'	=> 'Left',
				'center'  => 'Center',
			),
		),
		'title_right_spacing' => array(
			'title'				=> 'Right Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 60,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
		),
	),
	'description-options' => array(
		'title'  	 => 'Description Formatting',
		'break'		 => '2,2,2,2',
		'data-hide-mobile' => true,
		'style-class'=> 'ep-collapsed',
		'description_color' => array(
			'title'				=> 'Text Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#777777',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'accordion'
		),
		'description_text_transform' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Text Transform',
			'size'		 => 'span2',
			'class'			=> 'editor-listen',
			'data-handler'	=> 'accordion',
			'default' 	 => 'none',
			'select-box-values' => array(
				'none'			=> 'None',
				'uppercase'		=> 'Uppercase',
				'lowercase'		=> 'Lowercase'
			),
		),
		'description_font_family' => array(
			'data-input-type' => 'select-fonts',
			'title'		 		=> 'Font Family',
			'size'		 		=> 'span2',
			'class'     		=> 'editor-listen',
			'data-handler'  	=> 'accordion',
			'default' 	 		=> 'none',
			'select-box-values' => $atts->fonts,
		),
		'description_font_size' => array(
			'title'			=> 'Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 20,
			'min'			=> 6,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'accordion',
			'data-range-slider' => 'accordion',
			'data-has-unit'	=> true,
		),
		'description_line_height' => array(
			'title'			=> 'Line Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 30,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'accordion',
			'data-range-slider' => 'accordion',
			'data-has-unit'	=> true,
		),
		'description_letter_spacing' => array(
			'title'				=> 'Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-has-unit'		=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-range-slider' => 'accordion'
		),
		'description_align' => array(
			'data-input-type' 			=> 'switch',
			'switch-type'				=> 'twoway',
			'title'		 				=> 'Align',
			'size'		 				=> 'span2',
			'class'						=> 'editor-listen',
			'data-handler'				=> 'accordion',
			'default' 	 				=> 'left',
			'switch-values' => array(
				'left'	=> 'Left',
				'center'  => 'Center',
			),
		),
		'description_spacing' => array(
			'title'				=> 'Top Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 20,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
		),
	),
	'separator-options' => array(
		'title'  	 => 'Separator',
		'break'		 => '2,2',
		'style-class'=> 'ep-collapsed',
		'data-hide-mobile' => true,
		'seperator_visibility' => array(
			'data-input-type' 			=> 'switch',
			'switch-type'				=> 'twoway',
			'title'		 				=> 'Visibility',
			'size'		 				=> 'span2',
			'class'						=> 'editor-listen',
			'data-handler'				=> 'accordion',
			'default' 	 				=> 'visible',
			'switch-values' => array(
				'visible'	=> 'Visible',
				'hidden'  	=> 'Hidden',
			),
		),
		'seperator_mode' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'First / Last Item',
			'size'		 => 'span2',
			'class'			=> 'editor-listen',
			'data-handler'	=> 'accordion',
			'default' 	 => 'hidden',
			'select-box-values' => array(
				'hidden'	=> 'Hide both',
				'top'		=> 'Show on first',
				'bottom' 	=> 'Show on last',
				'both'		=> 'Show both'
			),
		),
		'seperator_color' => array(
			'title'				=> 'Color',
			'data-css-attribute'=> 'border-color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#dddddd',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'accordion'
		),
		'seperator_height' => array(
			'data-css-attribute' => 'border-top-width',
			'title'			=> 'Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 1,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'	=> 'accordion',
			'data-has-unit'	=> true,
			'data-range-slider' => 'accordion',
		),
	),
	'expand-icon' => array(
		'title'  	 => 'Expand/Collapse Icon',
		'break'		 => '2,2,2',
		'data-hide-mobile' => true,
		'style-class'=> 'ep-collapsed',
		'icon_type' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Icon',
			'size'		 => 'span2',
			'class'			=> 'editor-listen',
			'data-handler'	=> 'accordion',
			'default' 	 => 'plus',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'plus,arrow,custom',
			'data-visibility-prefix'	=> 'ov-expand-icon',
			'select-box-values' => array(
				'plus'		=> 'Plus',
				'arrow'		=> 'Arrow',
				'custom'	=> 'Custom'
			),
		),
		'icon_color' => array(
			'title'				=> 'Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#000000',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'accordion',
			'help'				=> 'If you upload a custom icon, the \'Color\' option will not be applied.',
		),
		'icon_width' => array(
			'title'				=> 'Width',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 30,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
		),
		'icon_spacing' => array(
			'title'				=> 'Top Spacing',
			'size'				=> 'span2',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'default'			=> 10,
			'min'				=> 0,
			'max'				=> 999,
			'class'     		=> 'editor-listen',
			'data-handler'		=> 'accordion',
			'data-has-unit'		=> true,
			'data-range-slider' => 'accordion',
			'data-negative'		=> true,
		),
		'icon_expand' => array(
			'title'			=> 'Collapsed',
			'help'			=> 'Define your image for the \'Collapsed\' state.',
			'size'			=> 'span2',
			'data-input-type'	=> 'admin-image-upload',
			'default'		=> '',
			'data-upload'	=> 'accordion',
			'class'			=> 'editor-listen',
			'style-class'   => 'ce-upload-small hide-unsplash ov-expand-icon-custom'
		),
		'icon_collapse' => array(
			'title'			=> 'Expanded',
			'help'			=> 'Define your image for the \'Expanded\' state.<br /><br />No preview available.',
			'size'			=> 'span2',
			'data-input-type'	=> 'admin-image-upload',
			'default'		=> '',
			'data-upload'	=> 'accordion',
			'class'			=> 'editor-listen',
			'style-class'   => 'ce-upload-small hide-unsplash ov-expand-icon-custom'
		),
	),
	// mobile general options
	'accordion_general_responsive_lg' => $atts->get_mobile('accordion', 'Desktop', 'lg', array('type' => 'general')),
	'accordion_general_responsive_md' => $atts->get_mobile('accordion', 'Tablet Landscape', 'md', array('type' => 'general')),
	'accordion_general_responsive_sm' => $atts->get_mobile('accordion', 'Tablet Portrait', 'sm', array('type' => 'general')),
	'accordion_general_responsive_xs' => $atts->get_mobile('accordion', 'Mobile', 'xs', array('type' => 'general')),
	// mobile item options
	'accordion_item_responsive_lg' => $atts->get_mobile('accordion', 'Desktop', 'lg', array('type' => 'item')),
	'accordion_item_responsive_md' => $atts->get_mobile('accordion', 'Tablet Landscape', 'md', array('type' => 'item')),
	'accordion_item_responsive_sm' => $atts->get_mobile('accordion', 'Tablet Portrait', 'sm', array('type' => 'item')),
	'accordion_item_responsive_xs' => $atts->get_mobile('accordion', 'Mobile', 'xs', array('type' => 'item')),
	// mobile title options
	'accordion_title_responsive_lg' => $atts->get_mobile('accordion', '', 'lg', array('type' => 'title')),
	'accordion_title_responsive_md' => $atts->get_mobile('accordion', '', 'md', array('type' => 'title')),
	'accordion_title_responsive_sm' => $atts->get_mobile('accordion', '', 'sm', array('type' => 'title')),
	'accordion_title_responsive_xs' => $atts->get_mobile('accordion', '', 'xs', array('type' => 'title')),
	// mobile description options
	'accordion_description_responsive_lg' => $atts->get_mobile('accordion', '', 'lg', array('type' => 'description')),
	'accordion_description_responsive_md' => $atts->get_mobile('accordion', '', 'md', array('type' => 'description')),
	'accordion_description_responsive_sm' => $atts->get_mobile('accordion', '', 'sm', array('type' => 'description')),
	'accordion_description_responsive_xs' => $atts->get_mobile('accordion', '', 'xs', array('type' => 'description')),
	// mobile icon options
	'accordion_icon_responsive_lg' => $atts->get_mobile('accordion', '', 'lg', array('type' => 'icon')),
	'accordion_icon_responsive_md' => $atts->get_mobile('accordion', '', 'md', array('type' => 'icon')),
	'accordion_icon_responsive_sm' => $atts->get_mobile('accordion', '', 'sm', array('type' => 'icon')),
	'accordion_icon_responsive_xs' => $atts->get_mobile('accordion', '', 'xs', array('type' => 'icon')),
);

?>